name: CI

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Set up Rye
      run: |
        ./scripts/install-rye.sh
        echo "PATH=$PATH:$HOME/.rye/shims" >> $GITHUB_ENV

    - name: Install ruff
      run: |
        rye install ruff

    - name: Install dependencies
      run: |
        rye sync

    - name: Lint with make
      run: |
        make lint
