name: CI

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Set up Rye
      uses: sksat/setup-rye@v0.8.0

    - name: Set up uv
      run: |
        rye config --set-bool behavior.use-uv=true

    - name: Install ruff
      run: |
        rye install ruff

    - name: Install dependencies
      run: |
        rye sync

    - name: Lint with make
      run: |
        make lint
