name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'tag version'
        required: true

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
    - name: Create Tag
      run: |
        VERSION="${{ github.event.inputs.version }}"
        git tag $VERSION
        git push origin $VERSION
